title: AIPAD Workshop
description: AIPAD Workshop at MICCAI 2024
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
workshop:
  name: "AIPAD: AI in Pancreatic Disease Detection and Diagnosis"
  short: AIPAD
  host: "MICCAI 2024<br>Marrakesh, Morocco<br>October 6-10, 2024"
  logo_url: img/logomiccai.png
  submission_link: https://cmt3.research.microsoft.com/AIPAD2024
  dates:
    submission: June 24, 2024
    decision: July 15, 2024
    camera_ready: July 30, 2024
    workshop: October 10, 2024
  organizers:
    - name: Federica
      surname: Proietto Salanitri
      affiliation: University of Catania
      email: federica.proiettosalanitri@unict.it
      pic: img/federica.jpg
    - name: Serestina
      surname: Viriri
      affiliation: University of KwaZulu-Natal
      email: 
      pic: img/serestina_viriri.jpg
    - name: Ulas
      surname: Bagci
      affiliation: Northwestern University
      email: 
      pic: img/pic.jpg
    - name: Pallavi
      surname: Tiwari
      affiliation: University of Wisconsin-Madison
      email: 
      pic: img/pic.jpg
    - name: Boqing
      surname: Gong
      affiliation: Google
      email: 
      pic: img/pic.jpg
    - name: Concetto
      surname: Spampinato
      affiliation: University of Catania
      email: concetto.spampinato@unict.it
      pic: img/concetto.jpg
  pc:
    - name: Giovanni
      surname: Bellitto
      affiliation: University of Catania
    - name: Salvatore 
      surname: Calcagno
      affiliation: University of Catania
    - name: Tolga  
      surname: Cukur
      affiliation: Bilkent University
    - name: Rutger   
      surname: Hendrix
      affiliation: Università Campus Bio-Medico Rome
    - name: Davood
      surname: Karimi
      affiliation: Boston Children's Hospital
    - name: Aggelos 
      surname: Katsaggelos
      affiliation: Northwestern University
    - name: Raffaele 
      surname: Mineo
      affiliation: Università Campus Bio-Medico Rome
    - name: Simone 
      surname: Palazzo
      affiliation: University of Catania
    - name: Matteo   
      surname: Pennisi
      affiliation: Università Campus Bio-Medico Rome
    - name: Ziyue  
      surname: Xu
      affiliation: NVIDIA
    - name: Jing 
      surname: Yuan
      affiliation: Zhejiang University
  talks:
    - name: "Zongwei Zhou"
      affiliation: "Johns Hopkins University"
      pic: img/Zhou.jpeg
      title: "Analysis of Pancreatic Tumors by Synthesis"
      file_text: "PDF"
      file_url: 
      bio: "Zongwei Zhou is an assistant research scientist at Johns Hopkins University. He received his Ph.D. in Biomedical Informatics at Arizona State University in 2021. His research focuses on developing novel methods to reduce the annotation efforts for computer-aided detection and diagnosis. Zongwei received the AMIA Doctoral Dissertation Award in 2022, the Elsevier-MedIA Best Paper Award in 2020, and the MICCAI Young Scientist Award in 2019. In addition to seven U.S. patents, Zongwei has published over 30 peer-reviewed journal/conference articles, two of which have been ranked among the most popular articles in IEEE TMI and the highest-cited article in EJNMMI Research. He was named the top 2% of Scientists released by Stanford University in 2022 and 2023."
    - name: "Ulas Bagci"
      affiliation: "Northwestern University"
      pic: img/pic.jpg
      title: "TBA"
      file_text: "PDF"
      file_url: 
      bio: "Dr Ulas Bagci is an Associate Professor (with tenure) at the Northwestern University's Radiology Department at Chicago. He has courtesy appointments at BME, ECE of Northwestern, and CS departement of University of Central Florida. His research interests are artificial intelligence, machine learning and their applications in biomedical and clinical imaging. Dr. Bagci has more than 350 peer-reviewed articles on these topics.
      Previously, he was a staff scientist and lab co-manager at the National Institutes of Health’s radiology and imaging sciences department, center for infectious disease imaging. Dr. Bagci holds several NIH grants (R01s, U01s, R15, R21, R03)  (as Principal Investigator) and serves as a steering committee member of AIR (artificial intelligence resource) at the NIH. Dr. Bagci also serves as an area chair for MICCAI for several years and he is an associate editor of top-tier journals in his fields such as IEEE Trans. on Medical Imaging and Medical Image Analysis. Prof. Bagci teaches machine learning, advanced deep learning methods, computer and robot vision, and medical imaging courses. He has several international and national recognitions including best paper and reviewer awards."
  program:
    - time: "08:00"
      type: organizer
      desc: Welcome
    - time: "08:15"
      type: oral
      title: Pancreatic Vessel Landmark Detection in CT Angiography using Prior Anatomical Knowledge
      author: L. Rist, C. Homm, F. Lades, A. Ayala Hernandez, M. Sühling, E. G. S. Brandt, A. Maier, and O. Taubmann
    - time: "08:30"
      type: oral
      title: Artificial Intelligence in Pancreatic Disease Detection and Diagnosis
      author: E. Rapisarda, A. G. , S. Calcagno, D. Giordano
    - time: "08:45"
      type: oral
      title: Hybrid DeepLearning Model for Pancreatic Cancer Image Segmentation
      author: W. Bakasa, C. Kwenda, S. Viriri
    - time: "09:00"
      type: oral
      title: Leveraging SAM and Learnable Prompts for Pancreatic MRI Segmentation
      author: C. Delle Castelle, F. Spampinato, F. Proietto Salanitri, G. Bellitto, C. Spampinato
    - time: "09:15"
      type: oral
      title: Optimizing Synthetic Data for Enhanced Pancreatic Tumor Segmentation
      author: L. Peng, Z. Zhang, G. Durak, F. H. Miller, A. Medetalibeyoglu, M. B. Wallace, U. Bagci
    - time: "09:30"
      type: keynote
      author: Ulas Bagci
      affiliation: Northwestern University
    - time: "10:00"
      type: organizer
      desc: Coffee break
    - time: "10:30"
      type: keynote
      author: Zongwei Zhou
      affiliation: Johns Hopkins University
    - time: "11:00"
      type: keynote
      author: Camila Gonzalez
      affiliation: Stanford University
    - time: "11:40"
      type: oral
      title: Addressing catastrophic forgetting by modulating global batch normalization statistics for medical domain expansion
      author: S. Gupta, K. Chang, L. Qu, A. Rana et al
    - time: "11:55"
      type: oral
      title: Distribution-Aware Replay for Continual MRI Segmentation
      author: N. Lemke, C. Gonzalez, A. Mukhopadhyay, M. Mundt
    - time: "12:10"
      type: oral
      title: Exploring Wearable Emotion Recognition with Transformer-Based Continual Learning
      author: F. Rizza, G. Bellitto, S. Calcagno, S. Palazzo
    - time: "12:25"
      type: organizer
      desc: Closing remarks
  program2:
    - time: "08:00"
      type: organizer
      desc: Welcome
    - time: "08:10"
      type: orals
      desc: AIPAD Presentations (10 min + 5 Q&A)
      paper_list:
        - title: Pancreatic Vessel Landmark Detection in CT Angiography using Prior Anatomical Knowledge
          author: L. Rist, C. Homm, F. Lades, A. Ayala Hernandez, M. Sühling, E. G. S. Brandt, A. Maier, and O. Taubmann
        - title: Artificial Intelligence in Pancreatic Disease Detection and Diagnosis
          author: E. Rapisarda, A. G. , S. Calcagno, D. Giordano
        - title: Hybrid DeepLearning Model for Pancreatic Cancer Image Segmentation
          author: W. Bakasa, C. Kwenda, S. Viriri
        - title: Leveraging SAM and Learnable Prompts for Pancreatic MRI Segmentation
          author: C. Delle Castelle, F. Spampinato, F. Proietto Salanitri, G. Bellitto, C. Spampinato
        - title: Optimizing Synthetic Data for Enhanced Pancreatic Tumor Segmentation
          author: L. Peng, Z. Zhang, G. Durak, F. H. Miller, A. Medetalibeyoglu, M. B. Wallace, U. Bagci
    - time: "09:30"
      type: keynote
      ws: AIPAD
      author: Ulas Bagci
      affiliation: Northwestern University
    - time: "10:00"
      type: organizer
      desc: Coffee break
    - time: "10:30"
      type: keynote
      ws: PILM
      author: Camila Gonzalez
      affiliation: Stanford University
    - time: "11:10"
      type: keynote
      ws: AIPAD
      author: Zongwei Zhou
      affiliation: Johns Hopkins University
    - time: "11:40"
      type: orals
      desc: PILM Presentations (10 min + 5 Q&A)
      paper_list:
        - title: Addressing catastrophic forgetting by modulating global batch normalization statistics for medical domain expansion
          author: S. Gupta, K. Chang, L. Qu, A. Rana et al
        - title: Distribution-Aware Replay for Continual MRI Segmentation
          author: N. Lemke, C. Gonzalez, A. Mukhopadhyay, M. Mundt
        - title: Exploring Wearable Emotion Recognition with Transformer-Based Continual Learning
          author: F. Rizza, G. Bellitto, S. Calcagno, S. Palazzo
    - time: "12:25"
      type: organizer
      desc: Closing remarks
        
    
